version: '3.3'
services:
  flask:
    # Путь до Dockerfile
    build: ./
    # Имя для создаваемого контейнера
    container_name: flask-app
    # Перезапускаем сервис в случае падения 
    restart: on-failure
    # Прокладывам путь для файлов. Все файлы, которые хранятся у нас в 
    # директории, появятся в директории контейнера /app
    volumes:
      - ./:/app
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "5000:8080"
    
