apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask
  namespace: {{ .Release.Namespace }}
  labels:
    app: flask
spec:
  replicas: {{ .Values.flask.replicas }}
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: {{ .Release.Name }}-flask
        image: {{ .Values.flask.image }}:{{ .Values.flask.tag }}
        ports:
        - containerPort: 8080
