apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dep
  labels:
    app: flask
spec:
  replicas: {{ .Values.dep.replicas }}
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: {{ .Release.Name }}-cntr
        image: {{ .Values.dep.image }}:{{ .Values.dep.tag }}
        ports:
        - containerPort: 8080
#      imagePullSecrets:
 #     -  name: regcred
