apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: {{ .Release.Name }}-ing
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  {{- range .Values.ingress.rules }}
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-svc
                port:
                  name: http
  {{- end }}
