apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: flask
  type: NodePort
